apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: example-customeraddress-bronze
  namespace: processing
spec:
  type: Python
  mode: cluster
  image: "vsvale/example-bronze:1.0.0"
  imagePullPolicy: Always
  mainApplicationFile: "local:///app/customeraddress-bronze.py"
  sparkVersion: "3.1.1"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  hadoopConf:
    "fs.s3a.endpoint": "http://172.19.0.2:8686"
    "fs.s3a.access.key": "NPCwnCXfISZ5RlZr"
    "fs.s3a.secret.key": "A942l4bcUielsXbTDKN5NnGmKNyadoZA"
  driver:
    # cores: 1
    coreRequest: 250m
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    serviceAccount: default
  executor:
    # cores: 1
    coreRequest: 250m
    instances: 1
    memory: "512m"
    labels:
      version: 3.1.1