BOOTSTRAP_SERVERS = "edh-kafka-bootstrap.ingestion.svc.cluster.local:9092"
YUGABYTEDB_JDBC="jdbc:postgresql://yb-tservers.database.svc.Cluster.local:5433/salesdw"
YUGABYTEDB_USER="plumber"
YUGABYTEDB_PSWD="PlumberSDE"
S3ENDPOINT="http://172.19.0.2:8686"
S3ACCESSKEY="raat9cl2bEWhbgtQ"
S3SECRETKEY="zcJWBrrGkInYEWXf4Oc37tCIdJVeA0fb"
