apiVersion: v1
appVersion: 2.17.0.0-b24
description: YugabyteDB is the high-performance distributed SQL database for building
  global, internet-scale apps.
home: https://www.yugabyte.com
icon: https://avatars0.githubusercontent.com/u/17074854?s=200&v=4
maintainers:
- email: sanketh@yugabyte.com
  name: Sanketh Indarapu
- email: gjalla@yugabyte.com
  name: Govardhan Reddy Jalla
name: yugabyte
sources:
- https://github.com/yugabyte/yugabyte-db
version: 2.17.0
