apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-operator-ingress
  namespace: deepstorage
  labels:
    app: minio-operator
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /minio-operator
        pathType: Prefix
        backend:
          service:
            name: console
            port:
              number: 9090 