apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: example-dimsalesterritory-landing
  namespace: processing
spec:
  type: Python
  mode: cluster
  image: "vsvale/k8sexample:1.0.0"
  imagePullPolicy: Always
  mainApplicationFile: "local:///app/stream/dimsalesterritory-landing.py"
  sparkVersion: "3.1.1"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  hadoopConf:
    "fs.s3a.endpoint": "http://172.20.0.2:8686"
    "fs.s3a.access.key": "minio_user"
    "fs.s3a.secret.key": "miniok8sexample"
  driver:
    # cores: 1
    coreRequest: 100m
    coreLimit: "250m"
    memory: "500m"
    labels:
      version: 3.1.1
    serviceAccount: default
  executor:
    # cores: 1
    coreRequest: 500m
    instances: 1
    memory: "500m"
    labels:
      version: 3.1.1